# include "kmerpos.hpp"
# include <iostream>
# include "clipp.h"
# include <vector>
using namespace clipp; using std::cout; using std::string; using std::vector;


int main(int argc, char *argv[]){
    string kmerfile;        // jellyfish result dump
    std::vector<string> target_files;
    string output = "./";          //output path
    int t = 8;
    int k_size = 21;        //k-mer length
    bool strand = false;

    auto cli = (
        option("-t", "--threads").doc("Number of threads [8]") & value("threads", t),
        option("-k", "--kmer").doc("K-mer length [21]") & value("k-size", k_size),
        option("-C").set(strand).doc("dump file is generated by -C or not [false]"),
        option("-o").doc("Output path [./]") & value("outpath", output),
        value("input file", kmerfile).doc("Dump file of jellyfish result"),
        value("sequence file", target_files).doc("Query files for k-mer").repeatable(true)
    );

    auto fmt = doc_formatting{}
		.first_column(8)                           //left border column for text body
		.doc_column(30)                            //column where parameter docstring starts
		.last_column(100);

    if(!parse(argc, const_cast<char **>(argv), cli)) {
		cout << "Usage:\n" << usage_lines(cli, "kmerpos")
     << "\nOptions:\n" << documentation(cli,fmt) << "\nERROR: Required parameter missing\n";
		// throw "Division by zero condition!";
		exit(0);
	}
	
    read_kmer(kmerfile.c_str(),t,k_size);
    build_pos(target_files, output, k_size, strand, 1, t);
    return 0;

    
}
